version: 2
jobs:
    build:
        docker:
            - image: ubuntu:16.04
        steps:
            - checkout
            - run:
                name: Install build tools
                command: apt update && apt install -y build-essential
            - run:
                name: Run test
                command: make test
